#!/bin/bash

#dirname=`perl -e 'use Cwd "abs_path";print abs_path(shift)' ../../sdk/bin`

#export PATH=$dirname:$PATH
export JIRAHOME=/var/local/jira
export JIRAINSTALL=/opt/jira
export MAVEN_COLOR=true

export ATLAS_OPTS="-Dcom.sun.net.ssl.checkRevocation=false -Dmail.mime.decodeparameters=true -Dorg.slf4j.simpleLogger.defaultLogLevel=warn"
export MAVEN_OPTS="-Xms2048m -Xmx512m -Dcom.sun.net.ssl.checkRevocation=false -Dorg.slf4j.simpleLogger.defaultLogLevel=warn"
# -Djava.security.debug=certpath"

